# -*- coding: utf8 -*-

LOCK_EXPIRE = 120 # seconds
LOCK_UPDATE = 60 # seconds

# Constants
LOCK_STATUS_UPDATED = 1
LOCK_STATUS_EXPIRED = 2
LOCK_STATUS_LOCKED = 3
LOCK_STATUS_CREATED = 4
LOCK_DELTA_MODIFICATION = 5 # seconds
